/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcow

import (
	"encoding/json"
)

// checks if the EditFail2BanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditFail2BanRequest{}

// EditFail2BanRequest struct for EditFail2BanRequest
type EditFail2BanRequest struct {
	Attr *EditFail2BanRequestAttr `json:"attr,omitempty"`
	// has to be none
	Items interface{} `json:"items,omitempty"`
}

// NewEditFail2BanRequest instantiates a new EditFail2BanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditFail2BanRequest() *EditFail2BanRequest {
	this := EditFail2BanRequest{}
	return &this
}

// NewEditFail2BanRequestWithDefaults instantiates a new EditFail2BanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditFail2BanRequestWithDefaults() *EditFail2BanRequest {
	this := EditFail2BanRequest{}
	return &this
}

// GetAttr returns the Attr field value if set, zero value otherwise.
func (o *EditFail2BanRequest) GetAttr() EditFail2BanRequestAttr {
	if o == nil || IsNil(o.Attr) {
		var ret EditFail2BanRequestAttr
		return ret
	}
	return *o.Attr
}

// GetAttrOk returns a tuple with the Attr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditFail2BanRequest) GetAttrOk() (*EditFail2BanRequestAttr, bool) {
	if o == nil || IsNil(o.Attr) {
		return nil, false
	}
	return o.Attr, true
}

// HasAttr returns a boolean if a field has been set.
func (o *EditFail2BanRequest) HasAttr() bool {
	if o != nil && !IsNil(o.Attr) {
		return true
	}

	return false
}

// SetAttr gets a reference to the given EditFail2BanRequestAttr and assigns it to the Attr field.
func (o *EditFail2BanRequest) SetAttr(v EditFail2BanRequestAttr) {
	o.Attr = &v
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditFail2BanRequest) GetItems() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditFail2BanRequest) GetItemsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return &o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *EditFail2BanRequest) HasItems() bool {
	if o != nil && IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given interface{} and assigns it to the Items field.
func (o *EditFail2BanRequest) SetItems(v interface{}) {
	o.Items = v
}

func (o EditFail2BanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditFail2BanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attr) {
		toSerialize["attr"] = o.Attr
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableEditFail2BanRequest struct {
	value *EditFail2BanRequest
	isSet bool
}

func (v NullableEditFail2BanRequest) Get() *EditFail2BanRequest {
	return v.value
}

func (v *NullableEditFail2BanRequest) Set(val *EditFail2BanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditFail2BanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditFail2BanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditFail2BanRequest(val *EditFail2BanRequest) *NullableEditFail2BanRequest {
	return &NullableEditFail2BanRequest{value: val, isSet: true}
}

func (v NullableEditFail2BanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditFail2BanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


