/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcow

import (
	"encoding/json"
)

// checks if the CreateSenderDependentTransportsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSenderDependentTransportsRequest{}

// CreateSenderDependentTransportsRequest struct for CreateSenderDependentTransportsRequest
type CreateSenderDependentTransportsRequest struct {
	// the hostname of the smtp server with port
	Hostname *string `json:"hostname,omitempty"`
	// the password for the smtp user
	Password *string `json:"password,omitempty"`
	// the username used to authenticate
	Username *string `json:"username,omitempty"`
}

// NewCreateSenderDependentTransportsRequest instantiates a new CreateSenderDependentTransportsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSenderDependentTransportsRequest() *CreateSenderDependentTransportsRequest {
	this := CreateSenderDependentTransportsRequest{}
	return &this
}

// NewCreateSenderDependentTransportsRequestWithDefaults instantiates a new CreateSenderDependentTransportsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSenderDependentTransportsRequestWithDefaults() *CreateSenderDependentTransportsRequest {
	this := CreateSenderDependentTransportsRequest{}
	return &this
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *CreateSenderDependentTransportsRequest) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSenderDependentTransportsRequest) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *CreateSenderDependentTransportsRequest) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *CreateSenderDependentTransportsRequest) SetHostname(v string) {
	o.Hostname = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CreateSenderDependentTransportsRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSenderDependentTransportsRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CreateSenderDependentTransportsRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CreateSenderDependentTransportsRequest) SetPassword(v string) {
	o.Password = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *CreateSenderDependentTransportsRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSenderDependentTransportsRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *CreateSenderDependentTransportsRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *CreateSenderDependentTransportsRequest) SetUsername(v string) {
	o.Username = &v
}

func (o CreateSenderDependentTransportsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSenderDependentTransportsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableCreateSenderDependentTransportsRequest struct {
	value *CreateSenderDependentTransportsRequest
	isSet bool
}

func (v NullableCreateSenderDependentTransportsRequest) Get() *CreateSenderDependentTransportsRequest {
	return v.value
}

func (v *NullableCreateSenderDependentTransportsRequest) Set(val *CreateSenderDependentTransportsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSenderDependentTransportsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSenderDependentTransportsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSenderDependentTransportsRequest(val *CreateSenderDependentTransportsRequest) *NullableCreateSenderDependentTransportsRequest {
	return &NullableCreateSenderDependentTransportsRequest{value: val, isSet: true}
}

func (v NullableCreateSenderDependentTransportsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSenderDependentTransportsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


