/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcow

import (
	"encoding/json"
)

// checks if the DeleteDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteDomainRequest{}

// DeleteDomainRequest struct for DeleteDomainRequest
type DeleteDomainRequest struct {
	Items []string `json:"items,omitempty"`
}

// NewDeleteDomainRequest instantiates a new DeleteDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteDomainRequest() *DeleteDomainRequest {
	this := DeleteDomainRequest{}
	return &this
}

// NewDeleteDomainRequestWithDefaults instantiates a new DeleteDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteDomainRequestWithDefaults() *DeleteDomainRequest {
	this := DeleteDomainRequest{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DeleteDomainRequest) GetItems() []string {
	if o == nil || IsNil(o.Items) {
		var ret []string
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteDomainRequest) GetItemsOk() ([]string, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DeleteDomainRequest) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []string and assigns it to the Items field.
func (o *DeleteDomainRequest) SetItems(v []string) {
	o.Items = v
}

func (o DeleteDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableDeleteDomainRequest struct {
	value *DeleteDomainRequest
	isSet bool
}

func (v NullableDeleteDomainRequest) Get() *DeleteDomainRequest {
	return v.value
}

func (v *NullableDeleteDomainRequest) Set(val *DeleteDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDomainRequest(val *DeleteDomainRequest) *NullableDeleteDomainRequest {
	return &NullableDeleteDomainRequest{value: val, isSet: true}
}

func (v NullableDeleteDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


