/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcow

import (
	"encoding/json"
)

// checks if the EditDomainAdminACLRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditDomainAdminACLRequest{}

// EditDomainAdminACLRequest struct for EditDomainAdminACLRequest
type EditDomainAdminACLRequest struct {
	// contains the domain admin username you want to edit
	Items map[string]interface{} `json:"items,omitempty"`
	Attr *EditDomainAdminACLRequestAttr `json:"attr,omitempty"`
}

// NewEditDomainAdminACLRequest instantiates a new EditDomainAdminACLRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditDomainAdminACLRequest() *EditDomainAdminACLRequest {
	this := EditDomainAdminACLRequest{}
	return &this
}

// NewEditDomainAdminACLRequestWithDefaults instantiates a new EditDomainAdminACLRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditDomainAdminACLRequestWithDefaults() *EditDomainAdminACLRequest {
	this := EditDomainAdminACLRequest{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *EditDomainAdminACLRequest) GetItems() map[string]interface{} {
	if o == nil || IsNil(o.Items) {
		var ret map[string]interface{}
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDomainAdminACLRequest) GetItemsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Items) {
		return map[string]interface{}{}, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *EditDomainAdminACLRequest) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given map[string]interface{} and assigns it to the Items field.
func (o *EditDomainAdminACLRequest) SetItems(v map[string]interface{}) {
	o.Items = v
}

// GetAttr returns the Attr field value if set, zero value otherwise.
func (o *EditDomainAdminACLRequest) GetAttr() EditDomainAdminACLRequestAttr {
	if o == nil || IsNil(o.Attr) {
		var ret EditDomainAdminACLRequestAttr
		return ret
	}
	return *o.Attr
}

// GetAttrOk returns a tuple with the Attr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDomainAdminACLRequest) GetAttrOk() (*EditDomainAdminACLRequestAttr, bool) {
	if o == nil || IsNil(o.Attr) {
		return nil, false
	}
	return o.Attr, true
}

// HasAttr returns a boolean if a field has been set.
func (o *EditDomainAdminACLRequest) HasAttr() bool {
	if o != nil && !IsNil(o.Attr) {
		return true
	}

	return false
}

// SetAttr gets a reference to the given EditDomainAdminACLRequestAttr and assigns it to the Attr field.
func (o *EditDomainAdminACLRequest) SetAttr(v EditDomainAdminACLRequestAttr) {
	o.Attr = &v
}

func (o EditDomainAdminACLRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditDomainAdminACLRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Attr) {
		toSerialize["attr"] = o.Attr
	}
	return toSerialize, nil
}

type NullableEditDomainAdminACLRequest struct {
	value *EditDomainAdminACLRequest
	isSet bool
}

func (v NullableEditDomainAdminACLRequest) Get() *EditDomainAdminACLRequest {
	return v.value
}

func (v *NullableEditDomainAdminACLRequest) Set(val *EditDomainAdminACLRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditDomainAdminACLRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditDomainAdminACLRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditDomainAdminACLRequest(val *EditDomainAdminACLRequest) *NullableEditDomainAdminACLRequest {
	return &NullableEditDomainAdminACLRequest{value: val, isSet: true}
}

func (v NullableEditDomainAdminACLRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditDomainAdminACLRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


