/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailcow

import (
	"encoding/json"
)

// checks if the IssueDomainAdminSSOTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssueDomainAdminSSOTokenRequest{}

// IssueDomainAdminSSOTokenRequest struct for IssueDomainAdminSSOTokenRequest
type IssueDomainAdminSSOTokenRequest struct {
	// the username for the admin user
	Username map[string]interface{} `json:"username,omitempty"`
}

// NewIssueDomainAdminSSOTokenRequest instantiates a new IssueDomainAdminSSOTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssueDomainAdminSSOTokenRequest() *IssueDomainAdminSSOTokenRequest {
	this := IssueDomainAdminSSOTokenRequest{}
	return &this
}

// NewIssueDomainAdminSSOTokenRequestWithDefaults instantiates a new IssueDomainAdminSSOTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssueDomainAdminSSOTokenRequestWithDefaults() *IssueDomainAdminSSOTokenRequest {
	this := IssueDomainAdminSSOTokenRequest{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *IssueDomainAdminSSOTokenRequest) GetUsername() map[string]interface{} {
	if o == nil || IsNil(o.Username) {
		var ret map[string]interface{}
		return ret
	}
	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueDomainAdminSSOTokenRequest) GetUsernameOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Username) {
		return map[string]interface{}{}, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *IssueDomainAdminSSOTokenRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given map[string]interface{} and assigns it to the Username field.
func (o *IssueDomainAdminSSOTokenRequest) SetUsername(v map[string]interface{}) {
	o.Username = v
}

func (o IssueDomainAdminSSOTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssueDomainAdminSSOTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableIssueDomainAdminSSOTokenRequest struct {
	value *IssueDomainAdminSSOTokenRequest
	isSet bool
}

func (v NullableIssueDomainAdminSSOTokenRequest) Get() *IssueDomainAdminSSOTokenRequest {
	return v.value
}

func (v *NullableIssueDomainAdminSSOTokenRequest) Set(val *IssueDomainAdminSSOTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIssueDomainAdminSSOTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIssueDomainAdminSSOTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssueDomainAdminSSOTokenRequest(val *IssueDomainAdminSSOTokenRequest) *NullableIssueDomainAdminSSOTokenRequest {
	return &NullableIssueDomainAdminSSOTokenRequest{value: val, isSet: true}
}

func (v NullableIssueDomainAdminSSOTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssueDomainAdminSSOTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


